server:
  port: 8201
dubbo:
  application:
    name: dubbo-provider
  registry:
      address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
    serialization: protobuf
  scan:
    base-packages: com.study.dubbo
spring:
  application:
    name: dubbo-provider
